// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs37amq3Ff3ip-ggfoIXxgn98usMdntao',
    appId: '1:447406888990:web:51ef9f58150ca907ad360f',
    messagingSenderId: '447406888990',
    projectId: 'propsync-system-356ef',
    authDomain: 'propsync-system-356ef.firebaseapp.com',
    databaseURL: 'https://propsync-system-356ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'propsync-system-356ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWjWePA844yvwC4NAZ8EcqUsOqbWhwSXo',
    appId: '1:447406888990:android:e92c61ccf007dc71ad360f',
    messagingSenderId: '447406888990',
    projectId: 'propsync-system-356ef',
    databaseURL: 'https://propsync-system-356ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'propsync-system-356ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGYmoxDfHgZioCG1qTzYXRfqTkghh_XMQ',
    appId: '1:447406888990:ios:aafbfdf2e9c494cbad360f',
    messagingSenderId: '447406888990',
    projectId: 'propsync-system-356ef',
    databaseURL: 'https://propsync-system-356ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'propsync-system-356ef.appspot.com',
    iosBundleId: 'com.example.propsyncSystem',
  );
}
